### PR TITLE
Polishing and Add Test

### PR DESCRIPTION
**Pull request by garyrussell**

### CODE REVIEW

**Comment by artembilan** [comment]
Looks like Travis is based on the Maven.
So, that confirms that we still need to fix poms as well :smile:

**Comment by artembilan** [comment]
Otherwise, yes: LGTM!

**Comment by gregturn** [comment]
Run test/run.sh to get a complete test.

**Comment by artembilan** [comment]
He-he! I can't do that on Windows :smile:

**Comment by garyrussell** [comment]
Thanks - forgot to add the test deps to the poms (just did gradle).

**Pull request merged**
